# Site Temel Ayarları
title: Noradark Web Tasarım
description: Profesyonel ve uygun fiyatlı web tasarım hizmetleri
url: "https://www.noradark.shop"  # Sonunda / OLMAMALI
baseurl: ""  # Subpath kullanmıyorsanız boş bırakın

# GitHub Pages Özel Ayarları
remote_theme: jekyll-theme-minimal

# Dil ve Lokal Ayarları
locale: "tr_TR"
language: "tr"
timezone: "Europe/Istanbul"

# Build Ayarları
markdown: kramdown
permalink: pretty
future: false

# Eklentiler
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-optional-front-matter

# Google Analytics (GA4) - GÜNCELLENMİŞ KISIM
google_analytics: G-WPD243Y25V  # Tırnak işaretleri olmadan

# Varsayılanlar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      author: "Noradark"
