# Site Temel Ayarları
title: Noradark Web Tasarım
description: Profesyonel ve uygun fiyatlı web tasarım hizmetleri
url: "https://www.noradark.shop"  # Sonunda / OLMAMALI
baseurl: ""  # Subpath kullanmıyorsanız boş bırakın 

# GitHub Pages Özel Ayarları
remote_theme: jekyll-theme-minimal  # GitHub Pages için theme yerine remote_theme kullanın

# Dil ve Lokal Ayarları
locale: "tr_TR"
language: "tr"
timezone: "Europe/Istanbul"

# Build Ayarları
markdown: kramdown
permalink: pretty  # Veya /:title/ şeklinde özelleştirebilirsiniz
future: false  # Gelecek tarihli post'ları gösterme
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed  # RSS feed desteği
  - jekyll-optional-front-matter

# Collections Ayarları
collections:
  pages:
    output: true
    permalink: /:path/  # /sayfa/ şeklinde URL'ler için

# Google Analytics (GA4)
google_analytics: "G-WPD243Y25V"  # Ölçüm Kimliğiniz

# Varsayılanlar (Opsiyonel)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      author: "Noradark"

# Sitenin görünümü ile ilgili ayarlar
jekyll-theme-minimal:
  # Tema spesifik ayarlar buraya
