name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]  # Veya "master" kullanıyorsanız değiştirin

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build with Jekyll
        run: jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
